export const emojiMap: Map<string, string> = new Map([
    [":)", "😊"],
    [":(", "😔"],
    [":smile", "😊"],
    [":heart", "❤️"],
    [":sad", "🥺"],
    [":cry", "😢"],
    [":laugh", "😆"],
    [":haha", "😆"],
    [":hihi", "😁"],
    [":like", "👍"],
    [":dislike", "👎"],
    [":unlike", "👎"],
    [":accept", "✅"],
    [":anger", "😡"],
    [":rage:", "😡"],
    [":pout:", "😡"],
    [":wow", "😲"],
    [":joke", "🤡"],
    [":ok", "👌"],
    [":zzz", "😴"],
    [":idol", "😎"],
]);